version: 2.0

actions:
  build:
    type: script
    options:
      commands:
      - "./gradlew clean build \
      --refresh-dependencies \
      --no-daemon \
      --console plain \
      -Parchiva.credentials.user='${Q_ARCHIVA_USER}' \
      -Parchiva.credentials.pass='${Q_SECRET_ARCHIVA_PASSWORD}' \
      -Dorg.gradle.jvmargs='-Xms1024m -Xmx8192m' \
      -PGRADLE_USER_HOME='/root/.gradle' \
      -Dorg.gradle.jvmargs='-Xms1024m -Xmx8192m'"
    runtime:
      type: docker
      options:
        image: registry.ng.bluemix.net/build_tools/ci-base-images/jvm-trusty:latest

pipelines:
  default:
    actions:
    - build